### ISSUE TITLE
Missing initializer node

### ISSUE THREAD

**Issue by gary-bai** [rose-compiler/rose#100]
Reproducer:
```cpp
template<int N>
class A {};
template<>
class A<1> {
public:
  const static int data = 1;
};

template<int N>
class B {
  static const int data = A<N>::data;
};

void top()
{
  B<1> b;
}
```
Partial AST Dump:
```
SgTemplateInstantiationDecl:template<> class B< 1 > {private: static const int data;};
SgTemplateInstantiationDefn:template<> class B< 1 > {private: static const int data;}
SgTemplateVariableDeclaration:private: static const int data;
SgInitializedName:B < 1 > ::data
```
The initializer for `B<1>::data` is missing.
Affected version: rose-0.10.0.30

**Comment by tristanvdb** [comment]
Hi,

This issue is due to our frontend EDG: static members of template instantiations are only provided if they are referenced.
You can look at the following code instead:
`
template<int N>
class A {};

template<>
class A<1> {
  public:
    const static int dataA = 1;
};

template<int N>
class B {
  public:
    static const int dataB = A<N>::dataA;
};

void top() {
//  B<1> b;
  int a = B<1>::dataB;
}
`
Unfortunately their is no possibility to fix this (maybe future versions of EDG will fix this issue).

Thanks,
-Tristan
