### ISSUE TITLE
Merging multiple ASTs and/or loading/saving ASTs 

### ISSUE THREAD

**Issue by jacksonvanover** [rose-compiler/rose#153]
I am currently developing a tool built using multiple ROSE plugin actions; this tool targets a Fortran project involving many source files and requires multiple transformation passes over each of these source files. However, the repeated parsing/unparsing of the AST is very costly. Two questions then:

1. There is a single plugin action that is necessarily run on every source code file in the project; is it possible to incrementally construct a single AST for the entire project during this initial pass over everything?
2. Is it possible to skip the parsing/unparsing during each intermediate transformation pass and opt instead to adopt a plugin workflow akin to: (read-AST-from-disk) -> (modify) -> (write-AST-to-disk) and repeat that cycle?

Documentation pertaining to any existing AST merge mechanisms appears to be sparse. Any help on this is much appreciated. Thank you!

**Comment by tristanvdb** [comment]
There is such mechanism in ROSE but it is still in development.

Simply, any ROSE tool that uses ROSE's command-line parsing can use the following options:
 * `-rose:ast:write filename`: write the whole AST to `filename` before the unparsing (so after the plugin)
 * `-rose:ast:read file1,file2`: read ASTs from multiple files (after parsing any source file in the command and before applying the plugins)
 * `-rose:ast:merge`: trigger ROSE's AST merge algorithms (automatically on when using `-rose:ast:read`)
 
You can use these on the default `rose-compiler` executable alongside a plugin..

Now for problems:
 * it is being developed for C/C++, I have not tested on Fortran. ROSE's merge performs some "linking" tasks that might not be adapted to Fortran
 * there is a known issue with write-after-read preventing recursive merge (or pipeline like you seem to want). It trips an assertion  because ROSE's memory pool get corrupted. That assertion can be commented out "safely". I will be fixing this issue in the coming weeks.

**Comment by jacksonvanover** [comment]
Very helpful @tristanvdb , thank you for the prompt response. I will update this thread when I get around to trying the merge mechanism on the fortran project.
