### ISSUE TITLE
move linked pages to wiki

### ISSUE THREAD

**Issue by chunhualiao** [rose-compiler/rose#44]
On https://github.com/rose-compiler/rose/wiki/Software-Dependencies , there are quite some linked pages which are still refering to doxygen pages. 

Please gradually move the linked pages to this repo's wiki.

**Comment by AndrewXu22** [comment]
Sure, will add the linked pages to wiki.

**Comment by matzke1** [comment]
The installation info should be "moved", not "copied" to the wiki 
since
we don't want to maintain two copies.

The doxygen pages are generated from files in
$ROSE/docs/Rose/Installation. There might be references in various
places to the top-level doxygen installation instructions too, 
which is
the 100_Installation.dox file.

And for users that are already accustomed to reading the doxygen 
pages,
the top-level doxygen installation page should probably be 
replaced with
a link to the wiki installation page rather than being entirely 
removed.

--Robb

Andrew writes:
