### ISSUE TITLE
x87 support

### ISSUE THREAD

**Issue by Trass3r** [rose-compiler/rose#54]
Is it planned to implement more support for x87? At least for the instructions interacting with the rest of the non-float code.

```
Semantics exception: no dispatch ability for "fild" instruction: 4152BD: fild      [esp+0]
Semantics exception: no dispatch ability for "fdivp" instruction: 4152C1: fdivp     (1), (0)
Semantics exception: 64-bit FP values not supported yet: 4152C3: fstp      [esp+0]
```
https://github.com/rose-compiler/rose/blob/93075545a3810529149fcca189e0181f31017e93/src/midend/BinaryAnalysis/instructionSemantics/DispatcherX86.C#L920

**Comment by matzke1** [comment]
We don't have plans to add semantics for floating point instructions at this time.  Which semantic domain are you using (symbolic, concrete, ...)? Concrete is the easiest to add, but symbolic is probably more useful for analysis. Symbolic is difficult because SMT solvers generally don't have a theory specific to IEEE floating point.

**Comment by Trass3r** [comment]
Symbolic: https://github.com/cmu-sei/pharos/issues/36#issuecomment-520045726

**Comment by matzke1** [comment]
We're actually looking into floating point semantics for another architecture, so it's possible that some x86 floating point instructions could be implemented in the next couple months.
