### ISSUE TITLE
Excluding header files from AST traversal

### ISSUE THREAD

**Issue by Premas** [rose-compiler/rose#62]
I run my translator on input benchmark as follows

Parser -c adaminAdar_main.cc

However, I am getting the following error
/home/prema/Documents/benchmarks/Green-Marl/apps/output_cpp/src/common_main.h"
          , line 8: catastrophic error: cannot open source file "gm.h"
  #include "gm.h"
                 ^
Errors in Processing Input File: throwing an instance of "frontend_failed" exception due to syntax errors detected in the input code

 I do not want my translator to run on header files. Is there any way to skip traversing the header files.

**Comment by chunhualiao** [comment]
Hi, A ROSE-based translator for C/C++ first uses EDG to parse the input code to create a full AST, before any meaningful analysis or transformation on AST can be done.   EDG, like most other compiler frontends, requires the input code and its headers be available to work properly.  So you must provide the paths to the headers used by your input code (usually with the -I option) .   Otherwise you are asking something called parsing partial (incomplete) code, which might well still be a cutting edge, open research problem and not supported in general. 

Back to the title of your question "excluding header files from AST travesal",  the words really mean how to customize the traversal operation *after* EDG parses the code correctly and a full AST is created, this can be done as explained at https://en.wikibooks.org/wiki/ROSE_Compiler_Framework/FAQ#How_to_skip_system_headers_in_translation?
