### ISSUE TITLE
How can I unparse header files if I changed something in the header files?

### ISSUE THREAD

**Issue by seanchen1002** [rose-compiler/rose#67]
Hi, All,
According to my experience, header files cannot be unparsed even if I changed something in them?
Is there any possible way to unparse header files?
Thanks
-Sean

**Comment by chunhualiao** [comment]
There are experimental option:  -rose:unparseHeaderFiles -rose:unparseHeaderFilesRootFolder UNPARSED_HEADERS_DIR in tests/CompilerTests/UnparseHeadersTests

You can try it out and file bugs. 

This is a difficult problem:  a changed header has to be saved to another file since writing to the original header is very dangerous (imaging debugging a header translator which corrupts input headers). Then all other files/headers including the changed header have to be updated to use the new header file.
